<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.12" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.3.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AML.Core.Common\AML.Core.Common.csproj" />
    <ProjectReference Include="..\AML.Core.DataContract\AML.Core.DataContract.csproj" />
    <ProjectReference Include="..\AML.DTO\AML.DTO.csproj" />
    <ProjectReference Include="..\AML.ViewModel\AML.ViewModel.csproj" />
  </ItemGroup>

</Project>
