<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>9cb0cd63-fa93-4d16-a3a1-b38830702181</UserSecretsId>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\**" />
    <Compile Remove="Views\Corporate\CustomerMaster\**" />
    <Compile Remove="wwwroot\plugins\filterizr\**" />
    <Content Remove="Areas\**" />
    <Content Remove="Views\Corporate\CustomerMaster\**" />
    <Content Remove="wwwroot\plugins\filterizr\**" />
    <EmbeddedResource Remove="Areas\**" />
    <EmbeddedResource Remove="Views\Corporate\CustomerMaster\**" />
    <EmbeddedResource Remove="wwwroot\plugins\filterizr\**" />
    <None Remove="Areas\**" />
    <None Remove="Views\Corporate\CustomerMaster\**" />
    <None Remove="wwwroot\plugins\filterizr\**" />
    <TypeScriptCompile Remove="Areas\**" />
    <TypeScriptCompile Remove="Views\Corporate\CustomerMaster\**" />
    <TypeScriptCompile Remove="wwwroot\plugins\filterizr\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\Report\DigiSchedulerLogs.cshtml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\RiskV2\Index.cshtml" />
    <Content Remove="Views\RiskV2\RiskCreate1.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Files\Data-Customer Bulk upload Sample.xlsx" />
    <None Remove="Views\Kyc\yzcfe0h5.w4r~" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Files\Data-Customer Bulk upload Sample.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Ewra\InternalWatchList\Create.cshtml" />
    <None Include="Views\Kyc\CreateCorporateKyc.cshtml" />
    <None Include="Views\Kyc\CreateIndividualKyc.cshtml" />
    <None Include="Views\RiskV2\RiskCreate1.cshtml" />
    <None Include="Views\RiskV2\Index.cshtml" />
    <None Include="Views\Risk\Create.cshtml" />
    <None Include="Views\Risk\Index.cshtml" />
    <None Include="Views\TransactionScreening\Index.cshtml" />
    <None Include="Views\TransactionScreening\PendingCases.cshtml" />
    <None Include="Views\TransactionScreening\PendingTransactions.cshtml" />
    <None Include="Views\TransactionScreening\ProcessTransactionCase.cshtml" />
    <None Include="wwwroot\plugins\JMS\.gitignore" />
    <None Include="wwwroot\plugins\JMS\dist\js\bootstrap-multiselect.js" />
    <None Include="wwwroot\plugins\JMS\dist\js\bootstrap-multiselect.min.js" />
    <None Include="wwwroot\plugins\JMS\dist\less\bootstrap-multiselect.less" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\fontawesome-5.15.1-web\fa-brands-400.svg" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\fontawesome-5.15.1-web\fa-brands-400.woff2" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\fontawesome-5.15.1-web\fa-regular-400.svg" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\fontawesome-5.15.1-web\fa-regular-400.woff2" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\fontawesome-5.15.1-web\fa-solid-900.svg" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\fontawesome-5.15.1-web\fa-solid-900.woff2" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\glyphicons-halflings-regular.svg" />
    <None Include="wwwroot\plugins\JMS\docs\fonts\glyphicons-halflings-regular.woff2" />
    <None Include="wwwroot\plugins\JMS\docs\js\bootstrap.bundle-4.5.2.min.js" />
    <None Include="wwwroot\plugins\JMS\docs\js\jquery-2.2.4.min.js" />
    <None Include="wwwroot\plugins\JMS\docs\js\knockout-3.4.0.debug.js" />
    <None Include="wwwroot\plugins\JMS\docs\js\prettify.min.js" />
    <None Include="wwwroot\plugins\JMS\docs\js\require-2.3.5.min.js" />
    <None Include="wwwroot\plugins\JMS\docs\less\bootstrap-example.less" />
    <None Include="wwwroot\plugins\JMS\LICENSE.md" />
    <None Include="wwwroot\plugins\JMS\post.php" />
    <None Include="wwwroot\plugins\JMS\README.md" />
    <None Include="wwwroot\plugins\JMS\tests\karma.conf.js" />
    <None Include="wwwroot\plugins\JMS\tests\lib\jasmine-2.4.1\boot.js" />
    <None Include="wwwroot\plugins\JMS\tests\lib\jasmine-2.4.1\console.js" />
    <None Include="wwwroot\plugins\JMS\tests\lib\jasmine-2.4.1\jasmine-html.js" />
    <None Include="wwwroot\plugins\JMS\tests\lib\jasmine-2.4.1\jasmine.js" />
    <None Include="wwwroot\plugins\JMS\tests\lib\MIT.LICENSE" />
    <None Include="wwwroot\plugins\JMS\tests\spec\bootstrap-multiselect.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="bootstrap-rtl" Version="3.3.6" />
    <PackageReference Include="EPPlus.Core" Version="1.5.4" />
    <PackageReference Include="Fingers10.ExcelExport" Version="3.0.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.3.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.8" />
    <PackageReference Include="NToastNotify" Version="8.0.0" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="Select.HtmlToPdf.NetCore" Version="20.2.0" />
    <PackageReference Include="Twitter.Bootstrap.RTL" Version="3.0.0" />
    
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AML.Core.ServiceContract\AML.Core.ServiceContract.csproj" />
    <ProjectReference Include="..\AML.Core.Service\AML.Core.Service.csproj" />
    <ProjectReference Include="..\AML.DTO\AML.DTO.csproj" />
    <ProjectReference Include="..\AML.ViewModel\AML.ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Shared\AdminLTE\_MainNavigation.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Shared\AdminLTE\_MainNavigation.en.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Views\RiskV2\ApprovedRiskEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\RiskV2\ApprovedScreenLogEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\RiskV2\CaseTransferedEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\RiskV2\RiskEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\Risk\ApprovedRiskEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\Risk\ApprovedScreenLogEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\Risk\CaseTransferedEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\Risk\OTPEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\Risk\RiskEmailBody.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties wwwroot_4css_4alt_4adminlte_1components_1css_1map__JsonSchema="https://json.schemastore.org/ts-force-config.json" /></VisualStudio></ProjectExtensions>

</Project>
