<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AML.Core.Common\AML.Core.Common.csproj" />
    <ProjectReference Include="..\AML.Core.DataContract\AML.Core.DataContract.csproj" />
    <ProjectReference Include="..\AML.Core.RepositoryContract\AML.Core.RepositoryContract.csproj" />
    <ProjectReference Include="..\AML.Core.Repository\AML.Core.Repository.csproj" />
    <ProjectReference Include="..\AML.Core.ServiceContract\AML.Core.ServiceContract.csproj" />
    <ProjectReference Include="..\AML.DTO\AML.DTO.csproj" />
    <ProjectReference Include="..\AML.ViewModel\AML.ViewModel.csproj" />
  </ItemGroup>

</Project>
