<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.12" />
    <PackageReference Include="MongoDB.Bson" Version="2.28.0" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AML.Core.Common\AML.Core.Common.csproj" />
  </ItemGroup>

</Project>
