<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="AMLDB\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.12" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.1" />
  </ItemGroup>

</Project>
